from __future__ import annotations

import re
import sqlite3
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from app.core.database import connect_immutable_readonly_sqlite
from app.core.paths import DEFAULT_DB_PATH
from app.domains.retrieval.result_contracts import NotebookFragment, PublicEvidence


MAX_COHERENT_TEXT_CHARS = 2_400
_SENTENCE_END = re.compile(r"[.!?。！？](?:[\"'’”)]*)?(?=\s|$)")
_DEPENDENT_START = re.compile(
    r"^(?:where|which|and|whose|with|for which)\b",
    re.IGNORECASE,
)
_DEPENDENT_AFTER_SENTENCE = re.compile(
    r"[.!?]\s+(?P<clause>where|which|and|whose|with|for which)\b",
)
_CODE_GENERATION_NOTE = re.compile(
    r"\bGenerated by\b[^.!?]*?\.ipynb\.$",
    re.IGNORECASE,
)
_CAPTION_MARKER = re.compile(
    r"\b(?:Figure|Table)\s+\d+(?:\.\d+)?\s*[:.]",
    re.IGNORECASE,
)
_EQUATION_LABEL = re.compile(r"\(\d+\.\d+\)")
_EQUATION_CUE = re.compile(
    r"(?:^|(?<=[.!?])\s+)"
    r"(?P<cue>(?:Using\s+Equation\b|This\s+gives\b|"
    r"The\s+posterior\s+predictive\b|"
    r"The\s+predictive\s+distribution\b))",
    re.IGNORECASE,
)
_PAGE_HEADER = re.compile(
    r"^\d+(?:\.\d+)+\.\s+.+\*\s*$",
)
_PAGE_NUMBER = re.compile(r"^\d{1,4}$")
_BOOK_FOOTER = re.compile(
    r"[“\"][^”\"]+[”\"]\.\s*Online version\.",
    re.IGNORECASE,
)
_AUTHOR_FOOTER = re.compile(
    r"^Author:\s+.+(?:license|copyright|©|\(C\))",
    re.IGNORECASE,
)


@dataclass(frozen=True)
class CoherentPdfEvidence:
    text: str
    pdf_page: int | None
    page_label: str | None
    heading: str | None
    section: str | None
    context_before: str | None
    context_after: str | None


def serialize_public_evidence(
    fragment: NotebookFragment,
    *,
    selection_rank: int | None = None,
    include_context: bool = True,
    db_path: Path | None = None,
) -> PublicEvidence:
    """Serialize one internal fragment through the only public evidence whitelist."""

    coherent: CoherentPdfEvidence | None = None
    if fragment.source_type == "pdf_chunk":
        coherent = build_coherent_pdf_evidence(
            fragment,
            db_path=db_path or DEFAULT_DB_PATH,
        )
    return PublicEvidence(
        fragment_id=fragment.fragment_id,
        source_type=fragment.source_type,
        document_id=fragment.document_id,
        document_title=fragment.document_title,
        document_type=fragment.document_type,
        pdf_page=coherent.pdf_page if coherent else fragment.pdf_page,
        page_label=coherent.page_label if coherent else fragment.page_label,
        heading=coherent.heading if coherent else fragment.heading,
        section=coherent.section if coherent else fragment.section,
        coherent_text=coherent.text if coherent else None,
        user_note=fragment.note_text if fragment.source_type != "pdf_chunk" else None,
        selected_source_text=(
            fragment.selected_text if fragment.source_type != "pdf_chunk" else None
        ),
        context_before=(
            (coherent.context_before if coherent else fragment.context_before)
            if include_context
            else None
        ),
        context_after=(
            (coherent.context_after if coherent else fragment.context_after)
            if include_context
            else None
        ),
        tags=list(fragment.tags),
        provenance=_public_provenance(fragment),
        open_target=fragment.open_target,
        selection_rank=selection_rank,
    )


def build_coherent_pdf_evidence(
    fragment: NotebookFragment,
    *,
    db_path: Path = DEFAULT_DB_PATH,
    maximum_chars: int = MAX_COHERENT_TEXT_CHARS,
) -> CoherentPdfEvidence:
    fallback = CoherentPdfEvidence(
        text=_limit_complete(_clean_text(fragment.text), maximum_chars),
        pdf_page=fragment.pdf_page,
        page_label=fragment.page_label,
        heading=fragment.heading,
        section=fragment.section,
        context_before=_clean_optional(fragment.context_before),
        context_after=_clean_optional(fragment.context_after),
    )
    if fragment.chunk_id is None or fragment.document_id is None:
        return fallback
    try:
        with connect_immutable_readonly_sqlite(Path(db_path)) as connection:
            current = connection.execute(
                """
                SELECT id, document_id, chunk_index, heading_path, chunk_text,
                       overlap_before, overlap_after, pdf_page_start, pdf_page_end,
                       chapter_id
                FROM knowledge_chunks
                WHERE id = ? AND document_id = ?
                """,
                (fragment.chunk_id, fragment.document_id),
            ).fetchone()
            if current is None:
                return fallback
            previous_rows = _neighbors(
                connection,
                current,
                before=True,
                limit=8,
            )
            previous = previous_rows[0] if previous_rows else None
            following = _neighbor(connection, current, before=False)
    except (OSError, sqlite3.Error):
        return fallback

    prefix = str(current["overlap_before"] or "")
    completed_prefix = _completed_prefix(previous, prefix)
    text = completed_prefix + str(current["chunk_text"] or "")
    text = _strip_page_boilerplate(text)
    text, antecedent = _repair_dependent_boundary(
        text,
        previous_rows=previous_rows,
    )
    text = _trim_incomplete_start(text)
    context_before = _previous_context(previous, prefix)

    minimum_end = len(text)
    suffix = str(current["overlap_after"] or "")
    text = _join_words(text, suffix)
    remaining_following = ""
    following_start = len(text)
    if following is not None and not _has_sentence_end(text, minimum_end):
        following_text = str(following["chunk_text"] or "")
        remaining_following = _after_overlap(following_text, suffix)
        text = _join_words(text, remaining_following)
    text, consumed = _complete_end(text, minimum_end)
    context_after = _following_context(
        remaining_following,
        max(0, consumed - following_start),
    )
    text = _limit_complete(_clean_text(text), maximum_chars)

    page_values = [
        _int_or_none(current["pdf_page_start"]),
        _int_or_none(current["pdf_page_end"]),
    ]
    if prefix and previous is not None:
        page_values.extend(
            [_int_or_none(previous["pdf_page_start"]), _int_or_none(previous["pdf_page_end"])]
        )
    if remaining_following and following is not None:
        page_values.extend(
            [_int_or_none(following["pdf_page_start"]), _int_or_none(following["pdf_page_end"])]
        )
    if antecedent is not None:
        page_values.extend(
            [
                _int_or_none(antecedent["pdf_page_start"]),
                _int_or_none(antecedent["pdf_page_end"]),
            ]
        )
    pages = [value for value in page_values if value is not None]
    page_start = min(pages) if pages else fragment.pdf_page
    page_end = max(pages) if pages else fragment.pdf_page
    page_label = (
        str(page_start)
        if page_start is not None and page_end == page_start
        else f"{page_start}–{page_end}"
        if page_start is not None and page_end is not None
        else fragment.page_label
    )
    heading = _clean_optional(current["heading_path"]) or fragment.heading
    return CoherentPdfEvidence(
        text=text or fallback.text,
        pdf_page=page_start,
        page_label=page_label,
        heading=heading,
        section=heading or fragment.section,
        context_before=context_before,
        context_after=context_after,
    )


def _neighbor(
    connection: sqlite3.Connection,
    current: sqlite3.Row,
    *,
    before: bool,
) -> sqlite3.Row | None:
    rows = _neighbors(connection, current, before=before, limit=1)
    return rows[0] if rows else None


def _neighbors(
    connection: sqlite3.Connection,
    current: sqlite3.Row,
    *,
    before: bool,
    limit: int,
) -> list[sqlite3.Row]:
    operator = "<" if before else ">"
    direction = "DESC" if before else "ASC"
    rows = connection.execute(
        f"""
        SELECT id, document_id, chunk_index, heading_path, chunk_text,
               overlap_before, overlap_after, pdf_page_start, pdf_page_end,
               chapter_id
        FROM knowledge_chunks
        WHERE document_id = ? AND chunk_index {operator} ?
        ORDER BY chunk_index {direction}, id {direction}
        LIMIT ?
        """,
        (current["document_id"], current["chunk_index"], max(1, int(limit))),
    ).fetchall()
    result: list[sqlite3.Row] = []
    for row in rows:
        if not _same_section(current, row):
            break
        result.append(row)
    return result


def _same_section(current: sqlite3.Row, neighbor: sqlite3.Row) -> bool:
    current_chapter = _int_or_none(current["chapter_id"])
    neighbor_chapter = _int_or_none(neighbor["chapter_id"])
    if current_chapter is not None or neighbor_chapter is not None:
        return current_chapter == neighbor_chapter
    current_heading = _clean_optional(current["heading_path"])
    neighbor_heading = _clean_optional(neighbor["heading_path"])
    return not (current_heading and neighbor_heading) or current_heading == neighbor_heading


def _public_provenance(fragment: NotebookFragment) -> dict[str, Any]:
    source = {
        "pdf_chunk": "pdf",
        "zotero_annotation_comment": "zotero_annotation",
        "zotero_child_note": "zotero_note",
        "zotero_inspiration_note": "zotero_note",
    }[fragment.source_type]
    return {
        key: value
        for key, value in {
            "source": source,
            "document_title": fragment.document_title,
            "page": fragment.page_label or fragment.pdf_page,
            "zotero_item_key": fragment.zotero_item_key,
            "zotero_attachment_key": fragment.zotero_attachment_key,
            "annotation_key": fragment.zotero_annotation_key,
            "fragment_id": fragment.fragment_id,
        }.items()
        if value is not None
    }


def _join_words(left: str, right: str) -> str:
    if not left:
        return right
    if not right:
        return left
    if left[-1].isspace() or right[0].isspace():
        return left + right
    return left + " " + right


def _trim_incomplete_start(text: str) -> str:
    cleaned = text.lstrip()
    if not cleaned or not cleaned[0].islower():
        return cleaned
    match = _SENTENCE_END.search(cleaned)
    if match is None:
        return cleaned
    return cleaned[match.end() :].lstrip()


def _after_overlap(text: str, overlap: str) -> str:
    overlap = overlap.strip()
    if overlap:
        index = text.find(overlap)
        if index >= 0:
            return text[index + len(overlap) :]
    return text


def _has_sentence_end(text: str, minimum: int) -> bool:
    return _SENTENCE_END.search(text, min(minimum, len(text))) is not None


def _complete_end(text: str, minimum: int) -> tuple[str, int]:
    match = _SENTENCE_END.search(text, min(minimum, len(text)))
    if match is None:
        return text.rstrip(), len(text)
    return text[: match.end()].rstrip(), match.end()


def _previous_context(previous: sqlite3.Row | None, overlap: str) -> str | None:
    if previous is None:
        return None
    text = str(previous["chunk_text"] or "")
    if overlap:
        index = text.rfind(overlap)
        if index >= 0:
            text = text[:index]
    matches = list(_SENTENCE_END.finditer(text))
    if len(matches) < 2:
        return _clean_optional(text[-400:])
    return _clean_optional(text[matches[-2].end() : matches[-1].end()])


def _completed_prefix(previous: sqlite3.Row | None, overlap: str) -> str:
    if previous is None or not overlap:
        return overlap
    previous_text = str(previous["chunk_text"] or "")
    index = previous_text.rfind(overlap)
    if index < 0:
        return overlap
    starts = [match.end() for match in _SENTENCE_END.finditer(previous_text[:index])]
    start = starts[-1] if starts else 0
    # ``overlap_before`` is the authoritative hand-off boundary.  Some legacy
    # chunks retain additional text after that boundary (and the next chunk
    # begins with the continuation), so carrying the whole previous tail would
    # splice the continuation into the stale duplicate.
    return previous_text[start : index + len(overlap)].lstrip()


def _repair_dependent_boundary(
    text: str,
    *,
    previous_rows: list[sqlite3.Row],
) -> tuple[str, sqlite3.Row | None]:
    cleaned = _clean_text(text)
    if not cleaned:
        return cleaned, None

    dependent_start = _dependent_clause_start(cleaned)
    if dependent_start is None:
        return cleaned, None

    antecedent = _find_equation_antecedent(previous_rows)
    if antecedent is not None:
        equation_text, row = antecedent
        return _join_words(equation_text, cleaned[dependent_start:]), row

    match = _SENTENCE_END.search(cleaned, dependent_start)
    if match is None:
        return cleaned[:dependent_start].rstrip(), None
    prefix = cleaned[:dependent_start].rstrip()
    independent = cleaned[match.end() :].lstrip()
    return _join_words(prefix, independent), None


def _dependent_clause_start(text: str) -> int | None:
    direct = _DEPENDENT_START.match(text)
    if direct is not None:
        return direct.start()

    for match in _DEPENDENT_AFTER_SENTENCE.finditer(text):
        prefix = text[: match.start("clause")].rstrip()
        if _CODE_GENERATION_NOTE.search(prefix):
            return match.start("clause")
        sentence_start = _last_sentence_start(prefix)
        if _CAPTION_MARKER.search(prefix[sentence_start:]):
            return match.start("clause")
    return None


def _last_sentence_start(text: str) -> int:
    matches = list(_SENTENCE_END.finditer(text))
    if len(matches) < 2:
        return 0
    return matches[-2].end()


def _find_equation_antecedent(
    previous_rows: list[sqlite3.Row],
) -> tuple[str, sqlite3.Row] | None:
    for row in previous_rows:
        candidate = _extract_equation_context(
            _strip_page_boilerplate(str(row["chunk_text"] or ""))
        )
        if candidate:
            return candidate, row
    return None


def _extract_equation_context(text: str) -> str | None:
    cleaned = _clean_text(text)
    labels = list(_EQUATION_LABEL.finditer(cleaned))
    if not labels:
        return None
    end = labels[-1].end()
    candidate = cleaned[:end]
    if "=" not in candidate:
        return None

    cues = list(_EQUATION_CUE.finditer(candidate))
    if cues:
        start = cues[-1].start("cue")
    else:
        equation_index = candidate.rfind("=", 0, end)
        starts = [
            match.end()
            for match in _SENTENCE_END.finditer(candidate[:equation_index])
        ]
        start = starts[-1] if starts else 0
    extracted = candidate[start:end].strip()
    if _CAPTION_MARKER.search(extracted):
        return None
    return extracted or None


def _strip_page_boilerplate(text: str) -> str:
    lines = str(text or "").splitlines()
    result: list[str] = []
    skip_page_number = False
    for line in lines:
        stripped = line.strip()
        if not stripped:
            result.append(line)
            continue
        if _PAGE_HEADER.match(stripped):
            skip_page_number = True
            continue
        if skip_page_number and _PAGE_NUMBER.match(stripped):
            skip_page_number = False
            continue
        skip_page_number = False
        if _AUTHOR_FOOTER.match(stripped):
            continue
        footer = _BOOK_FOOTER.search(line)
        if footer is not None:
            prefix = line[: footer.start()].rstrip()
            if prefix:
                result.append(prefix)
            continue
        result.append(line)
    return "\n".join(result)


def _following_context(remaining: str, consumed: int) -> str | None:
    if not remaining:
        return None
    tail = remaining[min(consumed, len(remaining)) :].lstrip()
    match = _SENTENCE_END.search(tail)
    return _clean_optional(tail[: match.end()] if match else tail[:400])


def _limit_complete(text: str, maximum: int) -> str:
    if len(text) <= maximum:
        return text
    matches = [match for match in _SENTENCE_END.finditer(text[:maximum])]
    if matches:
        return text[: matches[-1].end()].rstrip()
    return text[:maximum].rstrip()


def _clean_text(value: Any) -> str:
    return " ".join(str(value or "").split())


def _clean_optional(value: Any) -> str | None:
    cleaned = _clean_text(value)
    return cleaned or None


def _int_or_none(value: Any) -> int | None:
    try:
        return int(value) if value is not None else None
    except (TypeError, ValueError):
        return None
